import { useState } from 'react';
import Button from '../components/Button';
import Modal from '../components/Modal';

function ModalPage() {
  const [showModal, setShowModal] = useState(false);

  const handleClick = () => {
    setShowModal(true);
  };

  const handleClose = () => {
    setShowModal(false);
  }

  const actionBar = <div>
    <Button onClick={handleClose} primary>I Accept</Button>
  </div>;
  const modal = <Modal onClose={handleClose} actionBar={actionBar}>
    <p>
      Here is some info for you.
    </p>
  </Modal>

  return (
    <div>
      <Button primary onClick={handleClick}>Open Modal</Button>
      {showModal && modal}
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel nisl ac dolor tincidunt auctor eget vitae nisl. Integer mattis est facilisis, feugiat nisl eget, gravida lorem. Curabitur convallis, elit quis ornare ullamcorper, ligula dolor efficitur felis, a accumsan lectus erat sed erat. Aenean sit amet tortor quis mi laoreet rhoncus. Nam eu iaculis elit. Sed porta magna ut consectetur ullamcorper. Quisque in pharetra erat. Nam commodo erat ac lacus condimentum, et porttitor nunc tristique. Sed vitae convallis mauris. Vivamus et porttitor mauris, a semper sapien. Aenean a nibh velit. Mauris dictum vel quam nec pellentesque. Cras molestie eros ultricies, dignissim justo non, mattis purus. Donec feugiat dolor ut neque vulputate ultricies. Cras consectetur dolor eu pellentesque cursus.</p>
    </div>
  );
}

export default ModalPage;